### GET CLIENTS
GET http://localhost:3000/clients

### GET CLIENT BY ID
GET http://localhost:3000/clients/1

### GET CLIENT BY DNI
GET http://localhost:3000/clients/dni/77653071B

### ADD CLIENT
POST http://localhost:3000/clients
Content-Type: application/json

{
    "dni": "77653071B",
    "name": "jose",
    "email": "jose@jose.com",
    "phone": "633338128"
}

### UPDATE CLIENT
PUT http://localhost:3000/clients/1
Content-Type: application/json

{
    "dni": "77653071B",
    "name": "josh",
    "email": "jose@jose.com",
    "phone": "633338128"
}

### DELETE CLIENT
DELETE http://localhost:3000/clients/1

### USER REGISTER
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Soy test",
    "username": "test2",
    "password": "tesssst"
}

### USER LOGIN
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "test2",
    "password": "tesssst"
}

### USER LOGOUT 
POST http://localhost:3000/users/logout