### USER CLIENT REGISTER (ACCESS: ALL)
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "client",
    "id_number": "12345678A",
    "phone": "111222333",
    "email": "client@example.com",
    "password": "client1234"
}

### USER OPERATOR REGISTER (ACCESS: ALL)
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "operator",
    "id_number": "87654321A",
    "phone": "333222111",
    "email": "operator@example.com",
    "password": "operator1234"
}



### USER CLIENT LOGIN (ACCESS: ALL)
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "client@example.com",
    "password": "client1234"
}

### USER OPERATOR LOGIN (ACCESS: ALL)
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "operator@example.com",
    "password": "operator1234"
}

### USER ADMIN LOGIN (ACCESS: ALL)
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin1234"
}



### GET USER BY ID (ACCESS: CLIENTS | OPERATOR | ADMIN)
// GET http://localhost:3000/users/1d04076f-c3a1-4d17-af52-dcd1a2adce9c

### GET USER BY EMAIL (ACCESS: CLIENTS | OPERATOR | ADMIN)
//GET http://localhost:3000/users/email/operator@example.com

### GET ALL USERS (ACCESS: ONLY ADMIN)
GET http://localhost:3000/users

### GET CLIENTS (ACCESS: OPERATOR | ADMIN)
GET http://localhost:3000/users/clients

### GET OPERATORS (ACCESS: ONLY ADMIN)
GET http://localhost:3000/users/operators



### ASCEND USER CLIENT TO OPERATOR (ACCESS: ONLY ADMIN)
PATCH http://localhost:3000/users/1d04076f-c3a1-4d17-af52-dcd1a2adce9c



### USER LOGOUT (ACCESS: ALL)
POST http://localhost:3000/users/logout



### DELETE USER (ACCESS: ONLY ADMIN)
DELETE http://localhost:3000/users/1934ab9b-a8ff-4161-a152-8cb9af52a924



### CREATE MATERIALS (ACCESS: ONLY ADMIN)
POST http://localhost:3000/materials/
Content-Type: application/json

{
    "price":1.5,
    "type":"test", 
    "weight":1500
}
### CREATE MACHINES (ACCESS: ONLY ADMIN)
POST http://localhost:3000/machines/
Content-Type: application/json

{
    "max_velocity":1000,
    "max_weight":100000000,
    "max_widht":3000,
    "price":1.5
}
