### GET CLIENTS
GET http://localhost:3000/clients

### GET CLIENT BY ID
GET http://localhost:3000/clients/5f7123dd-885d-41a7-87cf-d4612cc0e490

### GET CLIENT BY DNI
GET http://localhost:3000/clients/dni/12345678A

### CREATE CLIENT
POST http://localhost:3000/clients
Content-Type: application/json

{
    "dni": "12345678A",
    "name": "jose",
    "email": "jose@jose.com",
    "phone": "633338128"
}

### UPDATE CLIENT
PUT http://localhost:3000/clients/5f7123dd-885d-41a7-87cf-d4612cc0e490
Content-Type: application/json

{
    "name": "josh",
    "email": "jose@jose.com",
    "phone": "633338128"
}

### DELETE CLIENT
DELETE http://localhost:3000/clients/fc1dce25-3c7e-4e48-b805-baf2c2439432

### USER REGISTER
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Soy test",
    "email": "jose@jose.com",
    "password": "tesssst"
}

### USER LOGIN
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "jose@jose.com",
    "password": "tesssst"
}

### USER LOGOUT 
POST http://localhost:3000/users/logout

### DELETE USER
DELETE http://localhost:3000/users/4a91b19f-75eb-4343-8a84-d0e268f27479