### GET MACHINES (ACCESS: CLIENTS | OPERATORS | ADMIN)
GET http://localhost:3000/machines/

### GET MACHINE BY ID (ACCESS: CLIENTS | OPERATORS | ADMIN)
GET http://localhost:3000/machines/3a5876ec-57fc-476e-9e73-d144947a0f0f

### CREATE MACHINES (ACCESS: ONLY ADMIN)
POST http://localhost:3000/machines/
Content-Type: application/json

{
    "max_velocity":1000,
    "max_weight":100000000,
    "max_widht":3000,
    "price":1.5
}
