### GET MATERIALS (ACCESS: CLIENTS | OPERATORS | ADMIN)
GET http://localhost:3000/materials/

### GET MATERIAL BY ID (ACCESS: CLIENTS | OPERATORS | ADMIN)
GET http://localhost:3000/materials/89650944-da96-45ec-a7e5-674979b499ee

### CREATE MATERIALS (ACCESS: ONLY ADMIN)
POST http://localhost:3000/materials/
Content-Type: application/json

{
    "price":1.5,
    "type":"Multicapa", 
    "weight":1000
}