### CREATE ORDERS (ACCESS: CLIENTS | OPERATORS | ADMIN)
POST http://localhost:3000/orders
Content-Type: application/json

{
"id_product": "3b3b4b56-dc34-4afc-8c4b-83b97810cc3c",
"quantity": 10
}

### GET MY ORDERS (ACCESS: CLIENT | OPERATOR | ADMIN)
GET http://localhost:3000/orders/all/me

### GET MY ORDER (ACCESS: CLIENT | OPERATOR | ADMIN)
GET http://localhost:3000/orders/me/5fee4086-fa0a-4518-9ca9-56d3bb8739be

### SET PENDING ORDER (ACCESS: CLIENT | OPERATOR | ADMIN)
PATCH http://localhost:3000/orders/set/pending/efd0c940-bd75-4807-8941-2bf3be8ccf1f

### GET PENDING ORDER (ACCESS: OPERATOR | ADMIN)
GET http://localhost:3000/orders/pending

### SET ORDER TO OPERATOR (ACCESS: OPERATOR)
PATCH http://localhost:3000/orders/set/operator/efd0c940-bd75-4807-8941-2bf3be8ccf1f

### GET PREPARATION ORDER (ACCESS: OPERATOR | ADMIN)
GET http://localhost:3000/orders/preparation/efd0c940-bd75-4807-8941-2bf3be8ccf1f

### GET ORDERS TO OPERATOR (ACCESS: OPERATOR | ADMIN)
GET http://localhost:3000/orders/operator/orders/2d44410a-ae35-496d-9ac9-ebedd73cd2b8

### SET COMPLETE (ACCESS: OPERATOR | ADMIN)
PATCH http://localhost:3000/orders/set/complete/5fee4086-fa0a-4518-9ca9-56d3bb8739be

### GET ORDERS (ACCESS: ADMIN)
GET http://localhost:3000/orders/

### GET ORDERS BY ID (ACCESS: ADMIN)
GET http://localhost:3000/orders/5fee4086-fa0a-4518-9ca9-56d3bb8739be