### GET PRODUCTS (ACCESS: CLIENTS | OPERATORS | ADMIN)
GET http://localhost:3000/products/

### GET PRODUCTS BY ID (ACCESS: CLIENTS | OPERATORS | ADMIN)
GET http://localhost:3000/products/3b3b4b56-dc34-4afc-8c4b-83b97810cc3c

### CREATE PRODUCTS (ACCESS: ADMIN | OPERATOR)
POST http://localhost:3000/products/
Content-Type: application/json

{
    "base": "iron",
    "cover": "black",
    "id_machine": "3a5876ec-57fc-476e-9e73-d144947a0f0f",
    "id_material": "2182cd23-6133-4152-ab46-3b5f59bfb30d",
    "length": 100,
    "widht":1500
}
