### GET CLIENTS
GET http://localhost:3000/clients

### GET CLIENT BY ID
GET http://localhost:3000/clients/ea1fc9fd-872e-47b7-a7aa-8ef821eaf0ee

### GET CLIENT BY DNI
GET http://localhost:3000/clients/dni/12345678A

### ADD CLIENT
POST http://localhost:3000/clients
Content-Type: application/json

{
    "dni": "12345678A",
    "name": "jose",
    "email": "jose@jose.com",
    "phone": "633338128"
}

### UPDATE CLIENT
PUT http://localhost:3000/clients/ea1fc9fd-872e-47b7-a7aa-8ef821eaf0ee
Content-Type: application/json

{
    "name": "jose",
    "email": "jose@jose.com",
    "phone": "633338128"
}

### DELETE CLIENT
DELETE http://localhost:3000/clients/c11f3d97-7797-420a-bb34-7591e45068da

### USER REGISTER
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Soy test",
    "email": "jose@jose.com",
    "password": "tesssst"
}

### USER LOGIN
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "jose@jose.com",
    "password": "tesssst"
}

### USER LOGOUT 
POST http://localhost:3000/users/logout

### DELETE USER
DELETE http://localhost:3000/users/4a91b19f-75eb-4343-8a84-d0e268f27479